export const CATEGORIES = [
  { id: 'basics', name: 'Основы', icon: '📖', description: 'Базовые слова и фразы', level: 'A1', order: 1 },
  { id: 'food', name: 'Еда', icon: '🍎', description: 'Еда и напитки', level: 'A1', order: 2 },
  { id: 'travel', name: 'Путешествия', icon: '✈️', description: 'Транспорт и места', level: 'A1', order: 3 },
  { id: 'family', name: 'Семья', icon: '👨‍👩‍👧‍👦', description: 'Родственники и друзья', level: 'A1', order: 4 },
  { id: 'work', name: 'Работа', icon: '💼', description: 'Офис и карьера', level: 'A2', order: 5 },
  { id: 'nature', name: 'Природа', icon: '🌳', description: 'Окружающая среда', level: 'A1', order: 6 },
  { id: 'emotions', name: 'Эмоции', icon: '😊', description: 'Чувства и состояния', level: 'A2', order: 7 },
  { id: 'verbs_irregular', name: 'Неправильные глаголы', icon: '⚡', description: 'Особые глаголы', level: 'A2', order: 8 }
];

export const LESSONS = [
  { id: 'basics-1', categoryId: 'basics', name: 'Приветствия', order: 1, wordIds: [1,2,3,4,5,6,7,8], requiredXp: 0 },
  { id: 'basics-2', categoryId: 'basics', name: 'Знакомство', order: 2, wordIds: [9,10,11,12,13,14,15,16], requiredXp: 50 },
  { id: 'food-1', categoryId: 'food', name: 'Завтрак', order: 1, wordIds: [17,18,19,20,21,22,23,24], requiredXp: 100 },
  { id: 'food-2', categoryId: 'food', name: 'Обед', order: 2, wordIds: [25,26,27,28,29,30,31,32], requiredXp: 150 },
  { id: 'travel-1', categoryId: 'travel', name: 'Транспорт', order: 1, wordIds: [33,34,35,36,37,38,39,40], requiredXp: 200 },
  { id: 'travel-2', categoryId: 'travel', name: 'В городе', order: 2, wordIds: [41,42,43,44,45,46,47,48], requiredXp: 250 },
  { id: 'family-1', categoryId: 'family', name: 'Родственники', order: 1, wordIds: [49,50,51,52,53,54,55,56], requiredXp: 300 },
  { id: 'family-2', categoryId: 'family', name: 'Друзья', order: 2, wordIds: [57,58,59,60,61,62,63,64], requiredXp: 350 },
  { id: 'work-1', categoryId: 'work', name: 'Офис', order: 1, wordIds: [65,66,67,68,69,70,71,72], requiredXp: 400 },
  { id: 'work-2', categoryId: 'work', name: 'Карьера', order: 2, wordIds: [73,74,75,76,77,78,79,80], requiredXp: 450 },
  { id: 'nature-1', categoryId: 'nature', name: 'Погода', order: 1, wordIds: [81,82,83,84,85,86,87,88], requiredXp: 500 },
  { id: 'nature-2', categoryId: 'nature', name: 'Пейзаж', order: 2, wordIds: [89,90,91,92,93,94,95,96], requiredXp: 550 },
  { id: 'emotions-1', categoryId: 'emotions', name: 'Позитивные', order: 1, wordIds: [97,98,99,100,101,102,103,104], requiredXp: 600 },
  { id: 'emotions-2', categoryId: 'emotions', name: 'Негативные', order: 2, wordIds: [105,106,107,108,109,110,111,112], requiredXp: 650 },
  { id: 'verbs-1', categoryId: 'verbs_irregular', name: 'Топ глаголов', order: 1, wordIds: [113,114,115,116,117,118,119,120], requiredXp: 700 },
  { id: 'verbs-2', categoryId: 'verbs_irregular', name: 'Движение', order: 2, wordIds: [121,122,123,124,125,126,127,128], requiredXp: 750 }
];

export const WORDS = [
  // Basics (1-16)
  { id: 1, word: 'hello', transcription: '/həˈloʊ/', translation: 'привет', category: 'basics', level: 'A1', example: 'Hello, how are you?' },
  { id: 2, word: 'goodbye', transcription: '/ɡʊdˈbaɪ/', translation: 'до свидания', category: 'basics', level: 'A1', example: 'Goodbye, see you tomorrow.' },
  { id: 3, word: 'please', transcription: '/pliːz/', translation: 'пожалуйста', category: 'basics', level: 'A1', example: 'Water, please.' },
  { id: 4, word: 'thank you', transcription: '/θæŋk juː/', translation: 'спасибо', category: 'basics', level: 'A1', example: 'Thank you for your help.' },
  { id: 5, word: 'yes', transcription: '/jɛs/', translation: 'да', category: 'basics', level: 'A1', example: 'Yes, I do.' },
  { id: 6, word: 'no', transcription: '/noʊ/', translation: 'нет', category: 'basics', level: 'A1', example: 'No, I am not.' },
  { id: 7, word: 'sorry', transcription: '/ˈsɑːri/', translation: 'извините', category: 'basics', level: 'A1', example: 'Sorry, I am late.' },
  { id: 8, word: 'excuse me', transcription: '/ɪkˈskjuːz miː/', translation: 'простите', category: 'basics', level: 'A1', example: 'Excuse me, where is the bus stop?' },
  { id: 9, word: 'good morning', transcription: '/ɡʊd ˈmɔːrnɪŋ/', translation: 'доброе утро', category: 'basics', level: 'A1', example: 'Good morning, everyone.' },
  { id: 10, word: 'good night', transcription: '/ɡʊd naɪt/', translation: 'спокойной ночи', category: 'basics', level: 'A1', example: 'Good night, sleep well.' },
  { id: 11, word: 'how are you', transcription: '/haʊ ɑːr juː/', translation: 'как дела', category: 'basics', level: 'A1', example: 'Hi, how are you?' },
  { id: 12, word: 'nice to meet you', transcription: '/naɪs tuː miːt juː/', translation: 'рад встрече', category: 'basics', level: 'A1', example: 'Nice to meet you too.' },
  { id: 13, word: 'my name is', transcription: '/maɪ neɪm ɪz/', translation: 'меня зовут', category: 'basics', level: 'A1', example: 'My name is John.' },
  { id: 14, word: 'I understand', transcription: '/aɪ ˌʌndərˈstænd/', translation: 'я понимаю', category: 'basics', level: 'A1', example: 'Yes, I understand.' },
  { id: 15, word: 'I don\'t understand', transcription: '/aɪ doʊnt ˌʌndərˈstænd/', translation: 'я не понимаю', category: 'basics', level: 'A1', example: 'Sorry, I don\'t understand.' },
  { id: 16, word: 'help', transcription: '/hɛlp/', translation: 'помощь', category: 'basics', level: 'A1', example: 'I need some help.' },

  // Food (17-32)
  { id: 17, word: 'water', transcription: '/ˈwɔːtər/', translation: 'вода', category: 'food', level: 'A1', example: 'I want some water.' },
  { id: 18, word: 'bread', transcription: '/brɛd/', translation: 'хлеб', category: 'food', level: 'A1', example: 'Fresh bread.' },
  { id: 19, word: 'milk', transcription: '/mɪlk/', translation: 'молоко', category: 'food', level: 'A1', example: 'Milk with cereal.' },
  { id: 20, word: 'coffee', transcription: '/ˈkɔːfi/', translation: 'кофе', category: 'food', level: 'A1', example: 'Black coffee.' },
  { id: 21, word: 'tea', transcription: '/tiː/', translation: 'чай', category: 'food', level: 'A1', example: 'Green tea.' },
  { id: 22, word: 'apple', transcription: '/ˈæpl/', translation: 'яблоко', category: 'food', level: 'A1', example: 'A red apple.' },
  { id: 23, word: 'cheese', transcription: '/tʃiːz/', translation: 'сыр', category: 'food', level: 'A1', example: 'Cheese and bread.' },
  { id: 24, word: 'meat', transcription: '/miːt/', translation: 'мясо', category: 'food', level: 'A1', example: 'I don\'t eat meat.' },
  { id: 25, word: 'fish', transcription: '/fɪʃ/', translation: 'рыба', category: 'food', level: 'A1', example: 'Fresh fish.' },
  { id: 26, word: 'rice', transcription: '/raɪs/', translation: 'рис', category: 'food', level: 'A1', example: 'Rice with chicken.' },
  { id: 27, word: 'chicken', transcription: '/ˈtʃɪkɪn/', translation: 'курица', category: 'food', level: 'A1', example: 'Fried chicken.' },
  { id: 28, word: 'egg', transcription: '/ɛɡ/', translation: 'яйцо', category: 'food', level: 'A1', example: 'A boiled egg.' },
  { id: 29, word: 'sugar', transcription: '/ˈʃʊɡər/', translation: 'сахар', category: 'food', level: 'A1', example: 'Coffee with sugar.' },
  { id: 30, word: 'salt', transcription: '/sɔːlt/', translation: 'соль', category: 'food', level: 'A1', example: 'Pass the salt.' },
  { id: 31, word: 'butter', transcription: '/ˈbʌtər/', translation: 'сливочное масло', category: 'food', level: 'A1', example: 'Bread and butter.' },
  { id: 32, word: 'soup', transcription: '/suːp/', translation: 'суп', category: 'food', level: 'A1', example: 'Hot soup.' },

  // Travel (33-48)
  { id: 33, word: 'airport', transcription: '/ˈɛərpɔːrt/', translation: 'аэропорт', category: 'travel', level: 'A1', example: 'To the airport, please.' },
  { id: 34, word: 'hotel', transcription: '/hoʊˈtɛl/', translation: 'отель', category: 'travel', level: 'A1', example: 'A nice hotel.' },
  { id: 35, word: 'taxi', transcription: '/ˈtæksi/', translation: 'такси', category: 'travel', level: 'A1', example: 'Call a taxi.' },
  { id: 36, word: 'ticket', transcription: '/ˈtɪkɪt/', translation: 'билет', category: 'travel', level: 'A1', example: 'A train ticket.' },
  { id: 37, word: 'passport', transcription: '/ˈpæspɔːrt/', translation: 'паспорт', category: 'travel', level: 'A1', example: 'Your passport, please.' },
  { id: 38, word: 'map', transcription: '/mæp/', translation: 'карта', category: 'travel', level: 'A1', example: 'A city map.' },
  { id: 39, word: 'station', transcription: '/ˈsteɪʃn/', translation: 'станция', category: 'travel', level: 'A1', example: 'The train station.' },
  { id: 40, word: 'bus', transcription: '/bʌs/', translation: 'автобус', category: 'travel', level: 'A1', example: 'By bus.' },
  { id: 41, word: 'train', transcription: '/treɪn/', translation: 'поезд', category: 'travel', level: 'A1', example: 'A fast train.' },
  { id: 42, word: 'plane', transcription: '/pleɪn/', translation: 'самолет', category: 'travel', level: 'A1', example: 'Boarding the plane.' },
  { id: 43, word: 'restaurant', transcription: '/ˈrɛstrɑːnt/', translation: 'ресторан', category: 'travel', level: 'A1', example: 'An Italian restaurant.' },
  { id: 44, word: 'museum', transcription: '/mjuˈziːəm/', translation: 'музей', category: 'travel', level: 'A1', example: 'The art museum.' },
  { id: 45, word: 'beach', transcription: '/biːtʃ/', translation: 'пляж', category: 'travel', level: 'A1', example: 'A sandy beach.' },
  { id: 46, word: 'money', transcription: '/ˈmʌni/', translation: 'деньги', category: 'travel', level: 'A1', example: 'I have no money.' },
  { id: 47, word: 'price', transcription: '/praɪs/', translation: 'цена', category: 'travel', level: 'A1', example: 'What is the price?' },
  { id: 48, word: 'vacation', transcription: '/vəˈkeɪʃn/', translation: 'отпуск', category: 'travel', level: 'A1', example: 'On vacation.' },

  // Family (49-64)
  { id: 49, word: 'mother', transcription: '/ˈmʌðər/', translation: 'мама', category: 'family', level: 'A1', example: 'My mother is here.' },
  { id: 50, word: 'father', transcription: '/ˈfɑːðər/', translation: 'папа', category: 'family', level: 'A1', example: 'His father works.' },
  { id: 51, word: 'sister', transcription: '/ˈsɪstər/', translation: 'сестра', category: 'family', level: 'A1', example: 'Older sister.' },
  { id: 52, word: 'brother', transcription: '/ˈbrʌðər/', translation: 'брат', category: 'family', level: 'A1', example: 'Younger brother.' },
  { id: 53, word: 'son', transcription: '/sʌn/', translation: 'сын', category: 'family', level: 'A1', example: 'Their son.' },
  { id: 54, word: 'daughter', transcription: '/ˈdɔːtər/', translation: 'дочь', category: 'family', level: 'A1', example: 'Her daughter.' },
  { id: 55, word: 'husband', transcription: '/ˈhʌzbənd/', translation: 'муж', category: 'family', level: 'A1', example: 'My husband.' },
  { id: 56, word: 'wife', transcription: '/waɪf/', translation: 'жена', category: 'family', level: 'A1', example: 'His wife.' },
  { id: 57, word: 'child', transcription: '/tʃaɪld/', translation: 'ребенок', category: 'family', level: 'A1', example: 'A small child.' },
  { id: 58, word: 'baby', transcription: '/ˈbeɪbi/', translation: 'малыш', category: 'family', level: 'A1', example: 'A cute baby.' },
  { id: 59, word: 'friend', transcription: '/frɛnd/', translation: 'друг', category: 'family', level: 'A1', example: 'A good friend.' },
  { id: 60, word: 'grandmother', transcription: '/ˈɡrænmʌðər/', translation: 'бабушка', category: 'family', level: 'A1', example: 'My grandmother.' },
  { id: 61, word: 'grandfather', transcription: '/ˈɡrænfɑːðər/', translation: 'дедушка', category: 'family', level: 'A1', example: 'My grandfather.' },
  { id: 62, word: 'aunt', transcription: '/ænt/', translation: 'тетя', category: 'family', level: 'A1', example: 'Aunt Jane.' },
  { id: 63, word: 'uncle', transcription: '/ˈʌŋkl/', translation: 'дядя', category: 'family', level: 'A1', example: 'Uncle Tom.' },
  { id: 64, word: 'cousin', transcription: '/ˈkʌzn/', translation: 'двоюродный брат/сестра', category: 'family', level: 'A1', example: 'My cousin.' },

  // Work (65-80)
  { id: 65, word: 'office', transcription: '/ˈɔːfɪs/', translation: 'офис', category: 'work', level: 'A1', example: 'In the office.' },
  { id: 66, word: 'meeting', transcription: '/ˈmiːtɪŋ/', translation: 'встреча', category: 'work', level: 'A1', example: 'A team meeting.' },
  { id: 67, word: 'computer', transcription: '/kəmˈpjuːtər/', translation: 'компьютер', category: 'work', level: 'A1', example: 'Use a computer.' },
  { id: 68, word: 'email', transcription: '/ˈiːmeɪl/', translation: 'электронная почта', category: 'work', level: 'A1', example: 'Send an email.' },
  { id: 69, word: 'phone', transcription: '/foʊn/', translation: 'телефон', category: 'work', level: 'A1', example: 'A phone call.' },
  { id: 70, word: 'project', transcription: '/ˈprɑːdʒɛkt/', translation: 'проект', category: 'work', level: 'A1', example: 'A new project.' },
  { id: 71, word: 'manager', transcription: '/ˈmænɪdʒər/', translation: 'менеджер', category: 'work', level: 'A1', example: 'The manager.' },
  { id: 72, word: 'team', transcription: '/tiːm/', translation: 'команда', category: 'work', level: 'A1', example: 'A good team.' },
  { id: 73, word: 'salary', transcription: '/ˈsæləri/', translation: 'зарплата', category: 'work', level: 'A1', example: 'High salary.' },
  { id: 74, word: 'deadline', transcription: '/ˈdɛdlaɪn/', translation: 'крайний срок', category: 'work', level: 'A1', example: 'Meet a deadline.' },
  { id: 75, word: 'schedule', transcription: '/ˈskɛdʒuːl/', translation: 'расписание', category: 'work', level: 'A1', example: 'A busy schedule.' },
  { id: 76, word: 'report', transcription: '/rɪˈpɔːrt/', translation: 'отчет', category: 'work', level: 'A1', example: 'Write a report.' },
  { id: 77, word: 'client', transcription: '/ˈklaɪənt/', translation: 'клиент', category: 'work', level: 'A1', example: 'Meet a client.' },
  { id: 78, word: 'interview', transcription: '/ˈɪntərvjuː/', translation: 'собеседование', category: 'work', level: 'A1', example: 'A job interview.' },
  { id: 79, word: 'resume', transcription: '/rɪˈzuːm/', translation: 'резюме', category: 'work', level: 'A1', example: 'Send a resume.' },
  { id: 80, word: 'colleague', transcription: '/ˈkɑːliːɡ/', translation: 'коллега', category: 'work', level: 'A1', example: 'My colleague.' },

  // Nature (81-96)
  { id: 81, word: 'sun', transcription: '/sʌn/', translation: 'солнце', category: 'nature', level: 'A1', example: 'The sun shines.' },
  { id: 82, word: 'moon', transcription: '/muːn/', translation: 'луна', category: 'nature', level: 'A1', example: 'A full moon.' },
  { id: 83, word: 'star', transcription: '/stɑːr/', translation: 'звезда', category: 'nature', level: 'A1', example: 'A bright star.' },
  { id: 84, word: 'tree', transcription: '/triː/', translation: 'дерево', category: 'nature', level: 'A1', example: 'A tall tree.' },
  { id: 85, word: 'flower', transcription: '/ˈflaʊər/', translation: 'цветок', category: 'nature', level: 'A1', example: 'A red flower.' },
  { id: 86, word: 'river', transcription: '/ˈrɪvər/', translation: 'река', category: 'nature', level: 'A1', example: 'A long river.' },
  { id: 87, word: 'mountain', transcription: '/ˈmaʊntn/', translation: 'гора', category: 'nature', level: 'A1', example: 'A high mountain.' },
  { id: 88, word: 'sea', transcription: '/siː/', translation: 'море', category: 'nature', level: 'A1', example: 'The blue sea.' },
  { id: 89, word: 'rain', transcription: '/reɪn/', translation: 'дождь', category: 'nature', level: 'A1', example: 'Heavy rain.' },
  { id: 90, word: 'snow', transcription: '/snoʊ/', translation: 'снег', category: 'nature', level: 'A1', example: 'White snow.' },
  { id: 91, word: 'wind', transcription: '/wɪnd/', translation: 'ветер', category: 'nature', level: 'A1', example: 'Strong wind.' },
  { id: 92, word: 'sky', transcription: '/skaɪ/', translation: 'небо', category: 'nature', level: 'A1', example: 'A clear sky.' },
  { id: 93, word: 'forest', transcription: '/ˈfɔːrɪst/', translation: 'лес', category: 'nature', level: 'A1', example: 'A dark forest.' },
  { id: 94, word: 'garden', transcription: '/ˈɡɑːrdn/', translation: 'сад', category: 'nature', level: 'A1', example: 'A beautiful garden.' },
  { id: 95, word: 'bird', transcription: '/bɜːrd/', translation: 'птица', category: 'nature', level: 'A1', example: 'A small bird.' },
  { id: 96, word: 'animal', transcription: '/ˈænɪml/', translation: 'животное', category: 'nature', level: 'A1', example: 'A wild animal.' },

  // Emotions (97-112)
  { id: 97, word: 'happy', transcription: '/ˈhæpi/', translation: 'счастливый', category: 'emotions', level: 'A1', example: 'I am happy.' },
  { id: 98, word: 'sad', transcription: '/sæd/', translation: 'грустный', category: 'emotions', level: 'A1', example: 'She is sad.' },
  { id: 99, word: 'angry', transcription: '/ˈæŋɡri/', translation: 'злой', category: 'emotions', level: 'A1', example: 'He is angry.' },
  { id: 100, word: 'tired', transcription: '/ˈtaɪərd/', translation: 'уставший', category: 'emotions', level: 'A1', example: 'I am tired.' },
  { id: 101, word: 'excited', transcription: '/ɪkˈsaɪtɪd/', translation: 'взволнованный', category: 'emotions', level: 'A1', example: 'We are excited.' },
  { id: 102, word: 'afraid', transcription: '/əˈfreɪd/', translation: 'испуганный', category: 'emotions', level: 'A1', example: 'I am afraid.' },
  { id: 103, word: 'surprised', transcription: '/sərˈpraɪzd/', translation: 'удивленный', category: 'emotions', level: 'A1', example: 'She was surprised.' },
  { id: 104, word: 'bored', transcription: '/bɔːrd/', translation: 'скучающий', category: 'emotions', level: 'A1', example: 'I am bored.' },
  { id: 105, word: 'proud', transcription: '/praʊd/', translation: 'гордый', category: 'emotions', level: 'A1', example: 'I am proud of you.' },
  { id: 106, word: 'nervous', transcription: '/ˈnɜːrvəs/', translation: 'нервный', category: 'emotions', level: 'A1', example: 'He feels nervous.' },
  { id: 107, word: 'calm', transcription: '/kɑːm/', translation: 'спокойный', category: 'emotions', level: 'A1', example: 'Stay calm.' },
  { id: 108, word: 'lonely', transcription: '/ˈloʊnli/', translation: 'одинокий', category: 'emotions', level: 'A1', example: 'She feels lonely.' },
  { id: 109, word: 'grateful', transcription: '/ˈɡreɪtfl/', translation: 'благодарный', category: 'emotions', level: 'A1', example: 'I am grateful.' },
  { id: 110, word: 'jealous', transcription: '/ˈdʒɛləs/', translation: 'ревнивый', category: 'emotions', level: 'A1', example: 'He is jealous.' },
  { id: 111, word: 'confused', transcription: '/kənˈfjuːzd/', translation: 'запутанный', category: 'emotions', level: 'A1', example: 'I am confused.' },
  { id: 112, word: 'hopeful', transcription: '/ˈhoʊpfl/', translation: 'надеющийся', category: 'emotions', level: 'A1', example: 'We remain hopeful.' },

  // Verbs (113-128)
  { id: 113, word: 'be', transcription: '/biː/', translation: 'быть', category: 'verbs_irregular', level: 'A1', example: 'I will be there.' },
  { id: 114, word: 'begin', transcription: '/bɪˈɡɪn/', translation: 'начинать', category: 'verbs_irregular', level: 'A1', example: 'Let\'s begin.' },
  { id: 115, word: 'break', transcription: '/breɪk/', translation: 'ломать', category: 'verbs_irregular', level: 'A1', example: 'Don\'t break it.' },
  { id: 116, word: 'bring', transcription: '/brɪŋ/', translation: 'приносить', category: 'verbs_irregular', level: 'A1', example: 'Bring me water.' },
  { id: 117, word: 'build', transcription: '/bɪld/', translation: 'строить', category: 'verbs_irregular', level: 'A1', example: 'Build a house.' },
  { id: 118, word: 'buy', transcription: '/baɪ/', translation: 'покупать', category: 'verbs_irregular', level: 'A1', example: 'Buy some milk.' },
  { id: 119, word: 'catch', transcription: '/kætʃ/', translation: 'ловить', category: 'verbs_irregular', level: 'A1', example: 'Catch the ball.' },
  { id: 120, word: 'choose', transcription: '/tʃuːz/', translation: 'выбирать', category: 'verbs_irregular', level: 'A1', example: 'Choose one.' },
  { id: 121, word: 'come', transcription: '/kʌm/', translation: 'приходить', category: 'verbs_irregular', level: 'A1', example: 'Come here.' },
  { id: 122, word: 'do', transcription: '/duː/', translation: 'делать', category: 'verbs_irregular', level: 'A1', example: 'Do it now.' },
  { id: 123, word: 'draw', transcription: '/drɔː/', translation: 'рисовать', category: 'verbs_irregular', level: 'A1', example: 'Draw a picture.' },
  { id: 124, word: 'drink', transcription: '/drɪŋk/', translation: 'пить', category: 'verbs_irregular', level: 'A1', example: 'Drink water.' },
  { id: 125, word: 'drive', transcription: '/draɪv/', translation: 'водить', category: 'verbs_irregular', level: 'A1', example: 'Drive a car.' },
  { id: 126, word: 'eat', transcription: '/iːt/', translation: 'есть', category: 'verbs_irregular', level: 'A1', example: 'Eat your food.' },
  { id: 127, word: 'fall', transcription: '/fɔːl/', translation: 'падать', category: 'verbs_irregular', level: 'A1', example: 'Don\'t fall.' },
  { id: 128, word: 'feel', transcription: '/fiːl/', translation: 'чувствовать', category: 'verbs_irregular', level: 'A1', example: 'I feel good.' }
];

export const IRREGULAR_VERBS = [
  { id: 'iv-1', infinitive: 'be', pastSimple: 'was/were', pastParticiple: 'been', translation: 'быть', hint: 'Самый важный глагол!', group: 'ABB' },
  { id: 'iv-2', infinitive: 'begin', pastSimple: 'began', pastParticiple: 'begun', translation: 'начинать', hint: 'I - A - U', group: 'ABC' },
  { id: 'iv-3', infinitive: 'break', pastSimple: 'broke', pastParticiple: 'broken', translation: 'ломать', hint: '', group: 'ABC' },
  { id: 'iv-4', infinitive: 'bring', pastSimple: 'brought', pastParticiple: 'brought', translation: 'приносить', hint: '-ought', group: 'ABB' },
  { id: 'iv-5', infinitive: 'build', pastSimple: 'built', pastParticiple: 'built', translation: 'строить', hint: '-t', group: 'ABB' },
  { id: 'iv-6', infinitive: 'buy', pastSimple: 'bought', pastParticiple: 'bought', translation: 'покупать', hint: '-ought', group: 'ABB' },
  { id: 'iv-7', infinitive: 'catch', pastSimple: 'caught', pastParticiple: 'caught', translation: 'ловить', hint: '-aught', group: 'ABB' },
  { id: 'iv-8', infinitive: 'choose', pastSimple: 'chose', pastParticiple: 'chosen', translation: 'выбирать', hint: '', group: 'ABC' },
  { id: 'iv-9', infinitive: 'come', pastSimple: 'came', pastParticiple: 'come', translation: 'приходить', hint: 'как в настоящем', group: 'ABA' },
  { id: 'iv-10', infinitive: 'do', pastSimple: 'did', pastParticiple: 'done', translation: 'делать', hint: '', group: 'ABC' },
  { id: 'iv-11', infinitive: 'draw', pastSimple: 'drew', pastParticiple: 'drawn', translation: 'рисовать', hint: '-ew/-awn', group: 'ABC' },
  { id: 'iv-12', infinitive: 'drink', pastSimple: 'drank', pastParticiple: 'drunk', translation: 'пить', hint: 'I - A - U', group: 'ABC' },
  { id: 'iv-13', infinitive: 'drive', pastSimple: 'drove', pastParticiple: 'driven', translation: 'водить', hint: '', group: 'ABC' },
  { id: 'iv-14', infinitive: 'eat', pastSimple: 'ate', pastParticiple: 'eaten', translation: 'есть', hint: '', group: 'ABC' },
  { id: 'iv-15', infinitive: 'fall', pastSimple: 'fell', pastParticiple: 'fallen', translation: 'падать', hint: '', group: 'ABC' },
  { id: 'iv-16', infinitive: 'feel', pastSimple: 'felt', pastParticiple: 'felt', translation: 'чувствовать', hint: '-t', group: 'ABB' },
  { id: 'iv-17', infinitive: 'find', pastSimple: 'found', pastParticiple: 'found', translation: 'находить', hint: '', group: 'ABB' },
  { id: 'iv-18', infinitive: 'fly', pastSimple: 'flew', pastParticiple: 'flown', translation: 'летать', hint: '-ew/-own', group: 'ABC' },
  { id: 'iv-19', infinitive: 'forget', pastSimple: 'forgot', pastParticiple: 'forgotten', translation: 'забывать', hint: '', group: 'ABC' },
  { id: 'iv-20', infinitive: 'get', pastSimple: 'got', pastParticiple: 'gotten', translation: 'получать', hint: '', group: 'ABC' },
  { id: 'iv-21', infinitive: 'give', pastSimple: 'gave', pastParticiple: 'given', translation: 'давать', hint: '', group: 'ABC' },
  { id: 'iv-22', infinitive: 'go', pastSimple: 'went', pastParticiple: 'gone', translation: 'идти', hint: '', group: 'ABC' },
  { id: 'iv-23', infinitive: 'have', pastSimple: 'had', pastParticiple: 'had', translation: 'иметь', hint: '', group: 'ABB' },
  { id: 'iv-24', infinitive: 'hear', pastSimple: 'heard', pastParticiple: 'heard', translation: 'слышать', hint: '-d', group: 'ABB' },
  { id: 'iv-25', infinitive: 'keep', pastSimple: 'kept', pastParticiple: 'kept', translation: 'хранить', hint: '-t', group: 'ABB' },
  { id: 'iv-26', infinitive: 'know', pastSimple: 'knew', pastParticiple: 'known', translation: 'знать', hint: '-ew/-own', group: 'ABC' },
  { id: 'iv-27', infinitive: 'leave', pastSimple: 'left', pastParticiple: 'left', translation: 'оставлять/покидать', hint: '', group: 'ABB' },
  { id: 'iv-28', infinitive: 'make', pastSimple: 'made', pastParticiple: 'made', translation: 'делать', hint: '', group: 'ABB' },
  { id: 'iv-29', infinitive: 'meet', pastSimple: 'met', pastParticiple: 'met', translation: 'встречать', hint: '', group: 'ABB' },
  { id: 'iv-30', infinitive: 'pay', pastSimple: 'paid', pastParticiple: 'paid', translation: 'платить', hint: '', group: 'ABB' },
  { id: 'iv-31', infinitive: 'put', pastSimple: 'put', pastParticiple: 'put', translation: 'класть', hint: 'все одинаково', group: 'AAA' },
  { id: 'iv-32', infinitive: 'read', pastSimple: 'read', pastParticiple: 'read', translation: 'читать', hint: 'пишется так же, читается по-другому', group: 'AAA' },
  { id: 'iv-33', infinitive: 'run', pastSimple: 'ran', pastParticiple: 'run', translation: 'бежать', hint: 'как в настоящем', group: 'ABA' },
  { id: 'iv-34', infinitive: 'say', pastSimple: 'said', pastParticiple: 'said', translation: 'говорить', hint: '', group: 'ABB' },
  { id: 'iv-35', infinitive: 'see', pastSimple: 'saw', pastParticiple: 'seen', translation: 'видеть', hint: '', group: 'ABC' },
  { id: 'iv-36', infinitive: 'sell', pastSimple: 'sold', pastParticiple: 'sold', translation: 'продавать', hint: '', group: 'ABB' },
  { id: 'iv-37', infinitive: 'send', pastSimple: 'sent', pastParticiple: 'sent', translation: 'посылать', hint: '-t', group: 'ABB' },
  { id: 'iv-38', infinitive: 'sit', pastSimple: 'sat', pastParticiple: 'sat', translation: 'сидеть', hint: '', group: 'ABB' },
  { id: 'iv-39', infinitive: 'sleep', pastSimple: 'slept', pastParticiple: 'slept', translation: 'спать', hint: '-t', group: 'ABB' },
  { id: 'iv-40', infinitive: 'speak', pastSimple: 'spoke', pastParticiple: 'spoken', translation: 'говорить', hint: '', group: 'ABC' },
  { id: 'iv-41', infinitive: 'stand', pastSimple: 'stood', pastParticiple: 'stood', translation: 'стоять', hint: '', group: 'ABB' },
  { id: 'iv-42', infinitive: 'take', pastSimple: 'took', pastParticiple: 'taken', translation: 'брать', hint: '', group: 'ABC' },
  { id: 'iv-43', infinitive: 'teach', pastSimple: 'taught', pastParticiple: 'taught', translation: 'учить', hint: '-aught', group: 'ABB' },
  { id: 'iv-44', infinitive: 'tell', pastSimple: 'told', pastParticiple: 'told', translation: 'рассказывать', hint: '', group: 'ABB' },
  { id: 'iv-45', infinitive: 'think', pastSimple: 'thought', pastParticiple: 'thought', translation: 'думать', hint: '-ought', group: 'ABB' },
  { id: 'iv-46', infinitive: 'understand', pastSimple: 'understood', pastParticiple: 'understood', translation: 'понимать', hint: 'как stand', group: 'ABB' },
  { id: 'iv-47', infinitive: 'wake', pastSimple: 'woke', pastParticiple: 'woken', translation: 'просыпаться', hint: '', group: 'ABC' },
  { id: 'iv-48', infinitive: 'win', pastSimple: 'won', pastParticiple: 'won', translation: 'побеждать', hint: '', group: 'ABB' },
  { id: 'iv-49', infinitive: 'write', pastSimple: 'wrote', pastParticiple: 'written', translation: 'писать', hint: '', group: 'ABC' },
  { id: 'iv-50', infinitive: 'wear', pastSimple: 'wore', pastParticiple: 'worn', translation: 'носить', hint: '', group: 'ABC' }
];

export const ACHIEVEMENTS = [
  { id: 'first-lesson', name: 'Первый урок', description: 'Завершите первый урок', icon: '🎓', condition: 'lessonsCompleted >= 1' },
  { id: 'five-lessons', name: 'Студент', description: 'Завершите 5 уроков', icon: '📚', condition: 'lessonsCompleted >= 5' },
  { id: 'ten-lessons', name: 'Ученик', description: 'Завершите 10 уроков', icon: '🧠', condition: 'lessonsCompleted >= 10' },
  { id: 'twenty-five-lessons', name: 'Знаток', description: 'Завершите 25 уроков', icon: '👑', condition: 'lessonsCompleted >= 25' },
  { id: 'first-perfect', name: 'Идеально', description: 'Пройдите урок без ошибок', icon: '🎯', condition: 'perfectLessons >= 1' },
  { id: 'seven-day-streak', name: 'Неделя', description: 'Учитесь 7 дней подряд', icon: '🔥', condition: 'streak >= 7' },
  { id: 'thirty-day-streak', name: 'Месяц', description: 'Учитесь 30 дней подряд', icon: '📅', condition: 'streak >= 30' },
  { id: 'hundred-words', name: 'Словарный запас', description: 'Выучите 100 слов', icon: '📖', condition: 'masteredWords >= 100' },
  { id: 'five-hundred-xp', name: 'Опытный', description: 'Наберите 500 XP', icon: '⭐', condition: 'xp >= 500' },
  { id: 'thousand-xp', name: 'Мастер', description: 'Наберите 1000 XP', icon: '🌟', condition: 'xp >= 1000' },
  { id: 'all-basics', name: 'База пройдена', description: 'Завершите все уроки в категории Основы', icon: '✅', condition: 'category_basics_completed' },
  { id: 'speed-demon', name: 'Гонщик', description: 'Пройдите урок быстрее чем за 60 секунд', icon: '⚡', condition: 'fastestLesson <= 60' },
  { id: 'night-owl', name: 'Сова', description: 'Учитесь после 22:00', icon: '🦉', condition: 'nightStudy >= 1' },
  { id: 'early-bird', name: 'Жаворонок', description: 'Учитесь до 7:00', icon: '🌅', condition: 'morningStudy >= 1' }
];
